apiVersion: apps/v1
kind: Deployment
metadata:
  name: trinibuggy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trinibuggy
  template:
    metadata:
      labels:
        app: trinibuggy
    spec:
      containers:
      - name: trinibuggy
        image: 767397800495.dkr.ecr.us-east-2.amazonaws.com/trin
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: trinibuggy
    k8s-app:trinibuggy
  nametrinibuggy
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: trinibuggy
